### ISSUE TITLE
Does not show the button in Chrome and Firefox, Edge only

### ISSUE THREAD

**Issue by erivandosena** [abdo-host/bootstrap-show-password#1]
Why does Chrome and Firefox work for me? Does not show the button

**Comment by abdo-host** [comment]
Check demo link : http://jsfiddle.net/zkou4dej/

Are you use [Bootstrap 4](https://getbootstrap.com/docs/4.6/getting-started/introduction/) and [Fontawesome](https://fontawesome.com/icons?d=gallery)

**Comment by erivandosena** [comment]
I noticed that it works like this in pure html. As I'm using with Django
forms.Form, it doesn't work when the HMTL code is rendered from
{{form.as_p}}


Any solution for use with Django?


Erivando Sena



Em qua., 24 de mar. de 2021 às 14:29, Abdo Hamoud ***@***.***>
escreveu:

**Comment by abdo-host** [comment]
Can you write an example code, and we will fix it for you
